default:
    host:       "cluster0.lggfbgp.mongodb.net"   
    username:   "nckrocha"
    password:   "NicoPico!23"
    database:   "stock_analyzer"
    collection: "user_base_test"
production:
    host:       "cluster0.lggfbgp.mongodb.net"
    username:   "nckrocha"
    password:   "NicoPico!23"
    database:   "stock_analyzer"
    collection: "user_base"
